### ISSUE TITLE
[버그제보] 질문 생성창에서 커서 깜빡임

### ISSUE THREAD

**Issue by Hju95** [KernelSquare/Frontend#92]
![image](https://github.com/KernelSquare/Frontend/assets/59231743/f98f1cca-d7c4-4d69-b6fb-8b3eb841ba6e)
입력 칸이 아닌 곳 들에서도 커서 깜빡임이 나오고 있습니다.

**Comment by Hju95** [comment]
맥 특이현상일 수도..

**Comment by Ryan-TheLion** [comment]
접근성 설정 문제일 수 있어서 https://seeminglyjs.tistory.com/225 해당 링크와 같이 확인 요청 드림 => 해결 됨
