### ISSUE TITLE
[버그제보] 회원 가입 이메일의 아이디 부분에 자음만 들어가도 유효성 검증 통과하는 문제

### ISSUE THREAD

**Issue by mooncw** [KernelSquare/Frontend#95]
![image](https://github.com/KernelSquare/Frontend/assets/97713997/d14ca658-c192-45e1-b9a0-c462aeee24d6)
닉네임처럼 막아주시면 될 것 같습니다.

**Comment by Ryan-TheLion** [comment]
@mooncw 

안녕하세요

저희 커널스퀘어 서비스를 사랑해주셔서 감사합니다.

해당 이슈는 이번 이슈에 반영하여 수정 될 예정입니다.

앞으로도 많은 이용부탁드립니다.
