### ISSUE TITLE
[버그제보] 큰 화면, 작은 화면 검색 결과 다름

### ISSUE THREAD

**Issue by Hju95** [KernelSquare/Frontend#96]
화면 클 때 검색했을 때는 잘 나오는데
화면을 엄청 줄여서 같은 단어로 검색을 하면 undefined 로 검색됩니다.
![image](https://github.com/KernelSquare/Frontend/assets/59231743/b91dd848-1d87-48fd-bed4-98364717bc62)
백 문제 일 수 있음

**Comment by JeongwooHam** [comment]
해결되었습니다!
