### ISSUE TITLE
[버그제보] 신규 생성 아이디들 마이페이지 Readme.md 버튼 활성화가 안됨

### ISSUE THREAD

**Issue by Hju95** [KernelSquare/Frontend#97]
![image](https://github.com/KernelSquare/Frontend/assets/59231743/fd808e2e-e03c-469e-a8b6-a6a4675f4ad1)

마이페이지에서 readme.md 누를 시 마크다운 창이 안나옴

**Comment by JeongwooHam** [comment]
자기소개 content 값 없을 경우 발생했던 오류로 현재 해결해두었습니다!
