### ISSUE TITLE
[버그제보] 본인 답변 투표 가능한 상태

### ISSUE THREAD

**Issue by Hju95** [KernelSquare/Frontend#98]
본인의 답변에는 투표가 불가능해야합니다.

![image](https://github.com/KernelSquare/Frontend/assets/59231743/12ba29b8-984e-41f4-b632-929c4ee22020)

프론트. 백 둘 다 체크 로직 필요합니다.
백도 체크로직 구현 예정입니다.

**Comment by JeongwooHam** [comment]
반영해두었습니다!
